INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r1 ,123 ,13); 
INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r2 ,234 ,11);
INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r3 ,345 ,8.5);
INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r4 ,456 ,9);
INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r5 ,567 ,9.5);
INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r6 ,678 ,10);
INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r7 ,789 ,15);
INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r8 ,890 ,9.7);
INSERT INTO tblStudent(name ,studentID ,grade) VALUES (r9 ,901 ,9.3);